CREATE TABLE IF NOT EXISTS categories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    image_url VARCHAR(255),
    parent_id INT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (parent_id) REFERENCES categories(id)
);

CREATE TABLE IF NOT EXISTS brands (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    logo_url VARCHAR(255),
    website VARCHAR(255),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    sku VARCHAR(50),
    price DECIMAL(10, 2) NOT NULL,
    sale_price DECIMAL(10, 2),
    quantity INT DEFAULT 0,
    short_description VARCHAR(500),
    description TEXT,
    specifications TEXT,
    image VARCHAR(255),
    brand_id INT,
    category_id INT,
    is_featured TINYINT(1) DEFAULT 0,
    is_new TINYINT(1) DEFAULT 0,
    is_top TINYINT(1) DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (brand_id) REFERENCES brands(id),
    FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE TABLE IF NOT EXISTS product_images (
    id INT AUTO_INCREMENT PRIMARY KEY,
    product_id INT NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    sort_order INT DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS customers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    address VARCHAR(255) NOT NULL,
    city VARCHAR(100) NOT NULL,
    province VARCHAR(100) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders (
    id INT AUTO_INCREMENT PRIMARY KEY,
    customer_id INT NOT NULL,
    order_number VARCHAR(50) NOT NULL,
    total_amount DECIMAL(10, 2) NOT NULL,
    payment_method ENUM('online_payment', 'direct_check') NOT NULL,
    status ENUM('pending', 'processing', 'completed', 'cancelled') DEFAULT 'pending',
    additional_info TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES customers(id)
);

CREATE TABLE IF NOT EXISTS order_items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    order_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    subtotal DECIMAL(10, 2) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE IF NOT EXISTS cart (
    id INT AUTO_INCREMENT PRIMARY KEY,
    session_id VARCHAR(255) NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (product_id) REFERENCES products(id),
    UNIQUE KEY (session_id, product_id)
);

INSERT INTO categories (name, slug, description, parent_id) VALUES
('Làm sạch kép', 'lam-sach-kep', 'Sản phẩm làm sạch kép giúp loại bỏ lớp trang điểm và bụi bẩn hiệu quả', NULL),
('Dầu tẩy trang', 'dau-tay-trang', 'Dầu tẩy trang dành cho mọi loại da', 1),
('Nước tẩy rửa', 'nuoc-tay-rua', 'Nước tẩy rửa dịu nhẹ cho da', 1),
('Bông tẩy trang', 'bong-tay-trang', 'Bông tẩy trang mềm mại', 1);
INSERT INTO brands (name, slug, description, logo_url, website) VALUES
('Innisfree', 'innisfree', 'Thương hiệu mỹ phẩm thiên nhiên từ Hàn Quốc', 'logos/innisfree.png', 'https://innisfree.com'),
('Some By Mi', 'some-by-mi', 'Thương hiệu chăm sóc da nổi tiếng với sản phẩm AHA-BHA-PHA', 'logos/somebymi.png', 'https://somebymi.com'),
('The Face Shop', 'the-face-shop', 'Thương hiệu mỹ phẩm Hàn Quốc với sản phẩm đa dạng', 'logos/thefaceshop.png', 'https://thefaceshop.com'),
('COSRX', 'cosrx', 'Thương hiệu chăm sóc da với sản phẩm dịu nhẹ', 'logos/cosrx.png', 'https://cosrx.com'),
('Etude House', 'etude-house', 'Thương hiệu mỹ phẩm đáng yêu từ Hàn Quốc', 'logos/etudehouse.png', 'https://etudehouse.com');
-- Dầu tẩy trang (category_id = 2), 50 sản phẩm (31 thuộc "Da khô", 19 thuộc các loại da khác)
INSERT INTO products (name, slug, sku, price, sale_price, quantity, short_description, description, brand_id, category_id, is_featured, is_new, is_top) VALUES
('Dầu tẩy trang Innisfree Green Tea 1', 'dau-tay-trang-innisfree-green-tea-1', 'INN001', 350000, 320000, 50, 'Dầu tẩy trang dịu nhẹ cho da khô', 'Dầu tẩy trang chiết xuất trà xanh, giúp làm sạch sâu, dưỡng ẩm cho da khô', 1, 2, 1, 0, 1),
('Dầu tẩy trang Some By Mi AHA-BHA 1', 'dau-tay-trang-some-by-mi-aha-bha-1', 'SBM001', 400000, NULL, 30, 'Dầu tẩy trang cho da khô', 'Làm sạch lớp trang điểm cứng đầu, cấp ẩm cho da khô với AHA-BHA', 2, 2, 0, 1, 0),
('Dầu tẩy trang The Face Shop Rice Water 1', 'dau-tay-trang-the-face-shop-rice-water-1', 'TFS001', 300000, 280000, 40, 'Dầu tẩy trang dịu nhẹ cho da khô', 'Chiết xuất nước gạo, dưỡng ẩm sâu, phù hợp với da khô', 3, 2, 0, 0, 1),
('Dầu tẩy trang COSRX Pure Fit 1', 'dau-tay-trang-cosrx-pure-fit-1', 'CSR001', 450000, NULL, 20, 'Dầu tẩy trang cho da khô', 'Làm sạch nhẹ nhàng, cấp ẩm cho da khô, không gây kích ứng', 4, 2, 0, 0, 0),
('Dầu tẩy trang Etude House Real Art 1', 'dau-tay-trang-etude-house-real-art-1', 'ETH001', 380000, 350000, 25, 'Dầu tẩy trang cho da khô', 'Dầu tẩy trang dưỡng ẩm, làm sạch sâu cho da khô', 5, 2, 0, 1, 0),
('Dầu tẩy trang Innisfree Green Tea 2', 'dau-tay-trang-innisfree-green-tea-2', 'INN002', 350000, 320000, 50, 'Dầu tẩy trang dịu nhẹ cho da khô', 'Dầu tẩy trang chiết xuất trà xanh, giúp làm sạch sâu, dưỡng ẩm cho da khô', 1, 2, 1, 0, 1),
('Dầu tẩy trang Some By Mi AHA-BHA 2', 'dau-tay-trang-some-by-mi-aha-bha-2', 'SBM002', 400000, NULL, 30, 'Dầu tẩy trang cho da khô', 'Làm sạch lớp trang điểm cứng đầu, cấp ẩm cho da khô với AHA-BHA', 2, 2, 0, 1, 0),
('Dầu tẩy trang The Face Shop Rice Water 2', 'dau-tay-trang-the-face-shop-rice-water-2', 'TFS002', 300000, 280000, 40, 'Dầu tẩy trang dịu nhẹ cho da khô', 'Chiết xuất nước gạo, dưỡng ẩm sâu, phù hợp với da khô', 3, 2, 0, 0, 1),
('Dầu tẩy trang COSRX Pure Fit 2', 'dau-tay-trang-cosrx-pure-fit-2', 'CSR002', 450000, NULL, 20, 'Dầu tẩy trang cho da khô', 'Làm sạch nhẹ nhàng, cấp ẩm cho da khô, không gây kích ứng', 4, 2, 0, 0, 0),
('Dầu tẩy trang Etude House Real Art 2', 'dau-tay-trang-etude-house-real-art-2', 'ETH002', 380000, 350000, 25, 'Dầu tẩy trang cho da khô', 'Dầu tẩy trang dưỡng ẩm, làm sạch sâu cho da khô', 5, 2, 0, 1, 0),
('Dầu tẩy trang Innisfree Green Tea 3', 'dau-tay-trang-innisfree-green-tea-3', 'INN003', 350000, 320000, 50, 'Dầu tẩy trang dịu nhẹ cho da khô', 'Dầu tẩy trang chiết xuất trà xanh, giúp làm sạch sâu, dưỡng ẩm cho da khô', 1, 2, 1, 0, 1),
('Dầu tẩy trang Some By Mi AHA-BHA 3', 'dau-tay-trang-some-by-mi-aha-bha-3', 'SBM003', 400000, NULL, 30, 'Dầu tẩy trang cho da khô', 'Làm sạch lớp trang điểm cứng đầu, cấp ẩm cho da khô với AHA-BHA', 2, 2, 0, 1, 0),
('Dầu tẩy trang The Face Shop Rice Water 3', 'dau-tay-trang-the-face-shop-rice-water-3', 'TFS003', 300000, 280000, 40, 'Dầu tẩy trang dịu nhẹ cho da khô', 'Chiết xuất nước gạo, dưỡng ẩm sâu, phù hợp với da khô', 3, 2, 0, 0, 1),
('Dầu tẩy trang COSRX Pure Fit 3', 'dau-tay-trang-cosrx-pure-fit-3', 'CSR003', 450000, NULL, 20, 'Dầu tẩy trang cho da khô', 'Làm sạch nhẹ nhàng, cấp ẩm cho da khô, không gây kích ứng', 4, 2, 0, 0, 0),
('Dầu tẩy trang Etude House Real Art 3', 'dau-tay-trang-etude-house-real-art-3', 'ETH003', 380000, 350000, 25, 'Dầu tẩy trang cho da khô', 'Dầu tẩy trang dưỡng ẩm, làm sạch sâu cho da khô', 5, 2, 0, 1, 0),
('Dầu tẩy trang Innisfree Green Tea 4', 'dau-tay-trang-innisfree-green-tea-4', 'INN004', 350000, 320000, 50, 'Dầu tẩy trang dịu nhẹ cho da khô', 'Dầu tẩy trang chiết xuất trà xanh, giúp làm sạch sâu, dưỡng ẩm cho da khô', 1, 2, 1, 0, 1),
('Dầu tẩy trang Some By Mi AHA-BHA 4', 'dau-tay-trang-some-by-mi-aha-bha-4', 'SBM004', 400000, NULL, 30, 'Dầu tẩy trang cho da khô', 'Làm sạch lớp trang điểm cứng đầu, cấp ẩm cho da khô với AHA-BHA', 2, 2, 0, 1, 0),
('Dầu tẩy trang The Face Shop Rice Water 4', 'dau-tay-trang-the-face-shop-rice-water-4', 'TFS004', 300000, 280000, 40, 'Dầu tẩy trang dịu nhẹ cho da khô', 'Chiết xuất nước gạo, dưỡng ẩm sâu, phù hợp với da khô', 3, 2, 0, 0, 1),
('Dầu tẩy trang COSRX Pure Fit 4', 'dau-tay-trang-cosrx-pure-fit-4', 'CSR004', 450000, NULL, 20, 'Dầu tẩy trang cho da khô', 'Làm sạch nhẹ nhàng, cấp ẩm cho da khô, không gây kích ứng', 4, 2, 0, 0, 0),
('Dầu tẩy trang Etude House Real Art 4', 'dau-tay-trang-etude-house-real-art-4', 'ETH004', 380000, 350000, 25, 'Dầu tẩy trang cho da khô', 'Dầu tẩy trang dưỡng ẩm, làm sạch sâu cho da khô', 5, 2, 0, 1, 0),
('Dầu tẩy trang Innisfree Green Tea 5', 'dau-tay-trang-innisfree-green-tea-5', 'INN005', 350000, 320000, 50, 'Dầu tẩy trang dịu nhẹ cho da khô', 'Dầu tẩy trang chiết xuất trà xanh, giúp làm sạch sâu, dưỡng ẩm cho da khô', 1, 2, 1, 0, 1),
('Dầu tẩy trang Some By Mi AHA-BHA 5', 'dau-tay-trang-some-by-mi-aha-bha-5', 'SBM005', 400000, NULL, 30, 'Dầu tẩy trang cho da khô', 'Làm sạch lớp trang điểm cứng đầu, cấp ẩm cho da khô với AHA-BHA', 2, 2, 0, 1, 0),
('Dầu tẩy trang The Face Shop Rice Water 5', 'dau-tay-trang-the-face-shop-rice-water-5', 'TFS005', 300000, 280000, 40, 'Dầu tẩy trang dịu nhẹ cho da khô', 'Chiết xuất nước gạo, dưỡng ẩm sâu, phù hợp với da khô', 3, 2, 0, 0, 1),
('Dầu tẩy trang COSRX Pure Fit 5', 'dau-tay-trang-cosrx-pure-fit-5', 'CSR005', 450000, NULL, 20, 'Dầu tẩy trang cho da khô', 'Làm sạch nhẹ nhàng, cấp ẩm cho da khô, không gây kích ứng', 4, 2, 0, 0, 0),
('Dầu tẩy trang Etude House Real Art 5', 'dau-tay-trang-etude-house-real-art-5', 'ETH005', 380000, 350000, 25, 'Dầu tẩy trang cho da khô', 'Dầu tẩy trang dưỡng ẩm, làm sạch sâu cho da khô', 5, 2, 0, 1, 0),
('Dầu tẩy trang Innisfree Green Tea 6', 'dau-tay-trang-innisfree-green-tea-6', 'INN006', 350000, 320000, 50, 'Dầu tẩy trang dịu nhẹ cho da khô', 'Dầu tẩy trang chiết xuất trà xanh, giúp làm sạch sâu, dưỡng ẩm cho da khô', 1, 2, 1, 0, 1),
('Dầu tẩy trang Some By Mi AHA-BHA 6', 'dau-tay-trang-some-by-mi-aha-bha-6', 'SBM006', 400000, NULL, 30, 'Dầu tẩy trang cho da khô', 'Làm sạch lớp trang điểm cứng đầu, cấp ẩm cho da khô với AHA-BHA', 2, 2, 0, 1, 0),
('Dầu tẩy trang The Face Shop Rice Water 6', 'dau-tay-trang-the-face-shop-rice-water-6', 'TFS006', 300000, 280000, 40, 'Dầu tẩy trang dịu nhẹ cho da khô', 'Chiết xuất nước gạo, dưỡng ẩm sâu, phù hợp với da khô', 3, 2, 0, 0, 1),
('Dầu tẩy trang COSRX Pure Fit 6', 'dau-tay-trang-cosrx-pure-fit-6', 'CSR006', 450000, NULL, 20, 'Dầu tẩy trang cho da khô', 'Làm sạch nhẹ nhàng, cấp ẩm cho da khô, không gây kích ứng', 4, 2, 0, 0, 0),
('Dầu tẩy trang Etude House Real Art 6', 'dau-tay-trang-etude-house-real-art-6', 'ETH006', 380000, 350000, 25, 'Dầu tẩy trang cho da khô', 'Dầu tẩy trang dưỡng ẩm, làm sạch sâu cho da khô', 5, 2, 0, 1, 0),
('Dầu tẩy trang Innisfree Green Tea 7', 'dau-tay-trang-innisfree-green-tea-7', 'INN007', 350000, 320000, 50, 'Dầu tẩy trang dịu nhẹ cho da khô', 'Dầu tẩy trang chiết xuất trà xanh, giúp làm sạch sâu, dưỡng ẩm cho da khô', 1, 2, 1, 0, 1),
('Dầu tẩy trang Some By Mi AHA-BHA 7', 'dau-tay-trang-some-by-mi-aha-bha-7', 'SBM007', 400000, NULL, 30, 'Dầu tẩy trang cho da khô', 'Làm sạch lớp trang điểm cứng đầu, cấp ẩm cho da khô với AHA-BHA', 2, 2, 0, 1, 0),
-- Tổng cộng 31 sản phẩm "Da khô" cho "Dầu tẩy trang"

-- Dầu tẩy trang cho các loại da khác (19 sản phẩm)
('Dầu tẩy trang Innisfree Apple Seed 1', 'dau-tay-trang-innisfree-apple-seed-1', 'INN008', 320000, NULL, 35, 'Dầu tẩy trang cho da hỗn hợp', 'Làm sạch sâu, kiểm soát dầu cho da hỗn hợp', 1, 2, 0, 0, 0),
('Dầu tẩy trang Some By Mi Rose 1', 'dau-tay-trang-some-by-mi-rose-1', 'SBM008', 420000, 400000, 15, 'Dầu tẩy trang cho da nhạy cảm', 'Chiết xuất hoa hồng, làm dịu da nhạy cảm', 2, 2, 1, 0, 0),
('Dầu tẩy trang The Face Shop Herb 1', 'dau-tay-trang-the-face-shop-herb-1', 'TFS007', 310000, NULL, 45, 'Dầu tẩy trang cho da bình thường', 'Làm sạch nhẹ nhàng, phù hợp với da bình thường', 3, 2, 0, 0, 0),
('Dầu tẩy trang COSRX Low pH 1', 'dau-tay-trang-cosrx-low-ph-1', 'CSR007', 430000, 410000, 25, 'Dầu tẩy trang cho da nhạy cảm', 'Làm sạch với độ pH thấp, dịu nhẹ cho da nhạy cảm', 4, 2, 0, 0, 0),
('Dầu tẩy trang Etude House Olive 1', 'dau-tay-trang-etude-house-olive-1', 'ETH007', 360000, NULL, 30, 'Dầu tẩy trang cho da hỗn hợp', 'Chiết xuất dầu ô liu, kiểm soát dầu cho da hỗn hợp', 5, 2, 0, 0, 0),
('Dầu tẩy trang Innisfree Apple Seed 2', 'dau-tay-trang-innisfree-apple-seed-2', 'INN009', 320000, NULL, 35, 'Dầu tẩy trang cho da hỗn hợp', 'Làm sạch sâu, kiểm soát dầu cho da hỗn hợp', 1, 2, 0, 0, 0),
('Dầu tẩy trang Some By Mi Rose 2', 'dau-tay-trang-some-by-mi-rose-2', 'SBM009', 420000, 400000, 15, 'Dầu tẩy trang cho da nhạy cảm', 'Chiết xuất hoa hồng, làm dịu da nhạy cảm', 2, 2, 1, 0, 0),
('Dầu tẩy trang The Face Shop Herb 2', 'dau-tay-trang-the-face-shop-herb-2', 'TFS008', 310000, NULL, 45, 'Dầu tẩy trang cho da bình thường', 'Làm sạch nhẹ nhàng, phù hợp với da bình thường', 3, 2, 0, 0, 0),
('Dầu tẩy trang COSRX Low pH 2', 'dau-tay-trang-cosrx-low-ph-2', 'CSR008', 430000, 410000, 25, 'Dầu tẩy trang cho da nhạy cảm', 'Làm sạch với độ pH thấp, dịu nhẹ cho da nhạy cảm', 4, 2, 0, 0, 0),
('Dầu tẩy trang Etude House Olive 2', 'dau-tay-trang-etude-house-olive-2', 'ETH008', 360000, NULL, 30, 'Dầu tẩy trang cho da hỗn hợp', 'Chiết xuất dầu ô liu, kiểm soát dầu cho da hỗn hợp', 5, 2, 0, 0, 0),
('Dầu tẩy trang Innisfree Apple Seed 3', 'dau-tay-trang-innisfree-apple-seed-3', 'INN010', 320000, NULL, 35, 'Dầu tẩy trang cho da hỗn hợp', 'Làm sạch sâu, kiểm soát dầu cho da hỗn hợp', 1, 2, 0, 0, 0),
('Dầu tẩy trang Some By Mi Rose 3', 'dau-tay-trang-some-by-mi-rose-3', 'SBM010', 420000, 400000, 15, 'Dầu tẩy trang cho da nhạy cảm', 'Chiết xuất hoa hồng, làm dịu da nhạy cảm', 2, 2, 1, 0, 0),
('Dầu tẩy trang The Face Shop Herb 3', 'dau-tay-trang-the-face-shop-herb-3', 'TFS009', 310000, NULL, 45, 'Dầu tẩy trang cho da bình thường', 'Làm sạch nhẹ nhàng, phù hợp với da bình thường', 3, 2, 0, 0, 0),
('Dầu tẩy trang COSRX Low pH 3', 'dau-tay-trang-cosrx-low-ph-3', 'CSR009', 430000, 410000, 25, 'Dầu tẩy trang cho da nhạy cảm', 'Làm sạch với độ pH thấp, dịu nhẹ cho da nhạy cảm', 4, 2, 0, 0, 0),
('Dầu tẩy trang Etude House Olive 3', 'dau-tay-trang-etude-house-olive-3', 'ETH009', 360000, NULL, 30, 'Dầu tẩy trang cho da hỗn hợp', 'Chiết xuất dầu ô liu, kiểm soát dầu cho da hỗn hợp', 5, 2, 0, 0, 0),
('Dầu tẩy trang Innisfree Apple Seed 4', 'dau-tay-trang-innisfree-apple-seed-4', 'INN011', 320000, NULL, 35, 'Dầu tẩy trang cho da hỗn hợp', 'Làm sạch sâu, kiểm soát dầu cho da hỗn hợp', 1, 2, 0, 0, 0),
('Dầu tẩy trang Some By Mi Rose 4', 'dau-tay-trang-some-by-mi-rose-4', 'SBM011', 420000, 400000, 15, 'Dầu tẩy trang cho da nhạy cảm', 'Chiết xuất hoa hồng, làm dịu da nhạy cảm', 2, 2, 1, 0, 0),
('Dầu tẩy trang The Face Shop Herb 4', 'dau-tay-trang-the-face-shop-herb-4', 'TFS010', 310000, NULL, 45, 'Dầu tẩy trang cho da bình thường', 'Làm sạch nhẹ nhàng, phù hợp với da bình thường', 3, 2, 0, 0, 0),
('Dầu tẩy trang COSRX Low pH 4', 'dau-tay-trang-cosrx-low-ph-4', 'CSR010', 430000, 410000, 25, 'Dầu tẩy trang cho da nhạy cảm', 'Làm sạch với độ pH thấp, dịu nhẹ cho da nhạy cảm', 4, 2, 0, 0, 0),
-- Tổng cộng 50 sản phẩm cho "Dầu tẩy trang"

-- Nước tẩy rửa (category_id = 3), 30 sản phẩm
('Nước tẩy rửa Innisfree Jeju 1', 'nuoc-tay-rua-innisfree-jeju-1', 'INN012', 250000, NULL, 60, 'Nước tẩy rửa cho da bình thường', 'Làm sạch nhẹ nhàng, phù hợp với da bình thường', 1, 3, 0, 0, 0),
('Nước tẩy rửa Some By Mi Tea Tree 1', 'nuoc-tay-rua-some-by-mi-tea-tree-1', 'SBM012', 280000, 260000, 40, 'Nước tẩy rửa cho da nhạy cảm', 'Chiết xuất trà tràm, làm dịu da nhạy cảm', 2, 3, 0, 1, 1),
('Nước tẩy rửa The Face Shop Herb 1', 'nuoc-tay-rua-the-face-shop-herb-1', 'TFS011', 220000, NULL, 50, 'Nước tẩy rửa cho da hỗn hợp', 'Làm sạch và kiểm soát dầu cho da hỗn hợp', 3, 3, 0, 0, 0),
('Nước tẩy rửa COSRX Centella 1', 'nuoc-tay-rua-cosrx-centella-1', 'CSR011', 260000, 240000, 55, 'Nước tẩy rửa cho da nhạy cảm', 'Chiết xuất rau má, làm dịu da nhạy cảm', 4, 3, 0, 0, 0),
('Nước tẩy rửa Etude House Aloe 1', 'nuoc-tay-rua-etude-house-aloe-1', 'ETH010', 230000, NULL, 45, 'Nước tẩy rửa cho da bình thường', 'Chiết xuất lô hội, làm sạch nhẹ nhàng cho da bình thường', 5, 3, 0, 0, 0),
('Nước tẩy rửa Innisfree Jeju 2', 'nuoc-tay-rua-innisfree-jeju-2', 'INN013', 250000, NULL, 60, 'Nước tẩy rửa cho da bình thường', 'Làm sạch nhẹ nhàng, phù hợp với da bình thường', 1, 3, 0, 0, 0),
('Nước tẩy rửa Some By Mi Tea Tree 2', 'nuoc-tay-rua-some-by-mi-tea-tree-2', 'SBM013', 280000, 260000, 40, 'Nước tẩy rửa cho da nhạy cảm', 'Chiết xuất trà tràm, làm dịu da nhạy cảm', 2, 3, 0, 1, 1),
('Nước tẩy rửa The Face Shop Herb 2', 'nuoc-tay-rua-the-face-shop-herb-2', 'TFS012', 220000, NULL, 50, 'Nước tẩy rửa cho da hỗn hợp', 'Làm sạch và kiểm soát dầu cho da hỗn hợp', 3, 3, 0, 0, 0),
('Nước tẩy rửa COSRX Centella 2', 'nuoc-tay-rua-cosrx-centella-2', 'CSR012', 260000, 240000, 55, 'Nước tẩy rửa cho da nhạy cảm', 'Chiết xuất rau má, làm dịu da nhạy cảm', 4, 3, 0, 0, 0),
('Nước tẩy rửa Etude House Aloe 2', 'nuoc-tay-rua-etude-house-aloe-2', 'ETH011', 230000, NULL, 45, 'Nước tẩy rửa cho da bình thường', 'Chiết xuất lô hội, làm sạch nhẹ nhàng cho da bình thường', 5, 3, 0, 0, 0),
('Nước tẩy rửa Innisfree Jeju 3', 'nuoc-tay-rua-innisfree-jeju-3', 'INN014', 250000, NULL, 60, 'Nước tẩy rửa cho da bình thường', 'Làm sạch nhẹ nhàng, phù hợp với da bình thường', 1, 3, 0, 0, 0),
('Nước tẩy rửa Some By Mi Tea Tree 3', 'nuoc-tay-rua-some-by-mi-tea-tree-3', 'SBM014', 280000, 260000, 40, 'Nước tẩy rửa cho da nhạy cảm', 'Chiết xuất trà tràm, làm dịu da nhạy cảm', 2, 3, 0, 1, 1),
('Nước tẩy rửa The Face Shop Herb 3', 'nuoc-tay-rua-the-face-shop-herb-3', 'TFS013', 220000, NULL, 50, 'Nước tẩy rửa cho da hỗn hợp', 'Làm sạch và kiểm soát dầu cho da hỗn hợp', 3, 3, 0, 0, 0),
('Nước tẩy rửa COSRX Centella 3', 'nuoc-tay-rua-cosrx-centella-3', 'CSR013', 260000, 240000, 55, 'Nước tẩy rửa cho da nhạy cảm', 'Chiết xuất rau má, làm dịu da nhạy cảm', 4, 3, 0, 0, 0),
('Nước tẩy rửa Etude House Aloe 3', 'nuoc-tay-rua-etude-house-aloe-3', 'ETH012', 230000, NULL, 45, 'Nước tẩy rửa cho da bình thường', 'Chiết xuất lô hội, làm sạch nhẹ nhàng cho da bình thường', 5, 3, 0, 0, 0),
('Nước tẩy rửa Innisfree Jeju 4', 'nuoc-tay-rua-innisfree-jeju-4', 'INN015', 250000, NULL, 60, 'Nước tẩy rửa cho da bình thường', 'Làm sạch nhẹ nhàng, phù hợp với da bình thường', 1, 3, 0, 0, 0),
('Nước tẩy rửa Some By Mi Tea Tree 4', 'nuoc-tay-rua-some-by-mi-tea-tree-4', 'SBM015', 280000, 260000, 40, 'Nước tẩy rửa cho da nhạy cảm', 'Chiết xuất trà tràm, làm dịu da nhạy cảm', 2, 3, 0, 1, 1),
('Nước tẩy rửa The Face Shop Herb 4', 'nuoc-tay-rua-the-face-shop-herb-4', 'TFS014', 220000, NULL, 50, 'Nước tẩy rửa cho da hỗn hợp', 'Làm sạch và kiểm soát dầu cho da hỗn hợp', 3, 3, 0, 0, 0),
('Nước tẩy rửa COSRX Centella 4', 'nuoc-tay-rua-cosrx-centella-4', 'CSR014', 260000, 240000, 55, 'Nước tẩy rửa cho da nhạy cảm', 'Chiết xuất rau má, làm dịu da nhạy cảm', 4, 3, 0, 0, 0),
('Nước tẩy rửa Etude House Aloe 4', 'nuoc-tay-rua-etude-house-aloe-4', 'ETH013', 230000, NULL, 45, 'Nước tẩy rửa cho da bình thường', 'Chiết xuất lô hội, làm sạch nhẹ nhàng cho da bình thường', 5, 3, 0, 0, 0),
('Nước tẩy rửa Innisfree Jeju 5', 'nuoc-tay-rua-innisfree-jeju-5', 'INN016', 250000, NULL, 60, 'Nước tẩy rửa cho da bình thường', 'Làm sạch nhẹ nhàng, phù hợp với da bình thường', 1, 3, 0, 0, 0),
('Nước tẩy rửa Some By Mi Tea Tree 5', 'nuoc-tay-rua-some-by-mi-tea-tree-5', 'SBM016', 280000, 260000, 40, 'Nước tẩy rửa cho da nhạy cảm', 'Chiết xuất trà tràm, làm dịu da nhạy cảm', 2, 3, 0, 1, 1),
('Nước tẩy rửa The Face Shop Herb 5', 'nuoc-tay-rua-the-face-shop-herb-5', 'TFS015', 220000, NULL, 50, 'Nước tẩy rửa cho da hỗn hợp', 'Làm sạch và kiểm soát dầu cho da hỗn hợp', 3, 3, 0, 0, 0),
('Nước tẩy rửa COSRX Centella 5', 'nuoc-tay-rua-cosrx-centella-5', 'CSR015', 260000, 240000, 55, 'Nước tẩy rửa cho da nhạy cảm', 'Chiết xuất rau má, làm dịu da nhạy cảm', 4, 3, 0, 0, 0),
('Nước tẩy rửa Etude House Aloe 5', 'nuoc-tay-rua-etude-house-aloe-5', 'ETH014', 230000, NULL, 45, 'Nước tẩy rửa cho da bình thường', 'Chiết xuất lô hội, làm sạch nhẹ nhàng cho da bình thường', 5, 3, 0, 0, 0),
('Nước tẩy rửa Innisfree Jeju 6', 'nuoc-tay-rua-innisfree-jeju-6', 'INN017', 250000, NULL, 60, 'Nước tẩy rửa cho da bình thường', 'Làm sạch nhẹ nhàng, phù hợp với da bình thường', 1, 3, 0, 0, 0),
('Nước tẩy rửa Some By Mi Tea Tree 6', 'nuoc-tay-rua-some-by-mi-tea-tree-6', 'SBM017', 280000, 260000, 40, 'Nước tẩy rửa cho da nhạy cảm', 'Chiết xuất trà tràm, làm dịu da nhạy cảm', 2, 3, 0, 1, 1),
('Nước tẩy rửa The Face Shop Herb 6', 'nuoc-tay-rua-the-face-shop-herb-6', 'TFS016', 220000, NULL, 50, 'Nước tẩy rửa cho da hỗn hợp', 'Làm sạch và kiểm soát dầu cho da hỗn hợp', 3, 3, 0, 0, 0),
('Nước tẩy rửa COSRX Centella 6', 'nuoc-tay-rua-cosrx-centella-6', 'CSR016', 260000, 240000, 55, 'Nước tẩy rửa cho da nhạy cảm', 'Chiết xuất rau má, làm dịu da nhạy cảm', 4, 3, 0, 0, 0),
('Nước tẩy rửa Etude House Aloe 6', 'nuoc-tay-rua-etude-house-aloe-6', 'ETH015', 230000, NULL, 45, 'Nước tẩy rửa cho da bình thường', 'Chiết xuất lô hội, làm sạch nhẹ nhàng cho da bình thường', 5, 3, 0, 0, 0),
-- Tổng cộng 30 sản phẩm cho "Nước tẩy rửa"

-- Bông tẩy trang (category_id = 4), 20 sản phẩm
('Bông tẩy trang Innisfree Soft 1', 'bong-tay-trang-innisfree-soft-1', 'INN018', 150000, 120000, 100, 'Bông tẩy trang mềm mại', 'Bông tẩy trang mềm mại, phù hợp với mọi loại da', 1, 4, 0, 0, 1),
('Bông tẩy trang The Face Shop Pure 1', 'bong-tay-trang-the-face-shop-pure-1', 'TFS017', 130000, NULL, 80, 'Bông tẩy trang cho da nhạy cảm', 'Bông tẩy trang dịu nhẹ, không gây kích ứng cho da nhạy cảm', 3, 4, 0, 0, 0),
('Bông tẩy trang COSRX Cotton 1', 'bong-tay-trang-cosrx-cotton-1', 'CSR017', 140000, 110000, 90, 'Bông tẩy trang cho da nhạy cảm', 'Bông tẩy trang mềm mại, không gây kích ứng cho da nhạy cảm', 4, 4, 0, 0, 0),
('Bông tẩy trang Etude House Pure 1', 'bong-tay-trang-etude-house-pure-1', 'ETH016', 120000, NULL, 70, 'Bông tẩy trang mềm mại', 'Bông tẩy trang mềm mại, phù hợp với mọi loại da', 5, 4, 0, 0, 0),
('Bông tẩy trang Innisfree Soft 2', 'bong-tay-trang-innisfree-soft-2', 'INN019', 150000, 120000, 100, 'Bông tẩy trang mềm mại', 'Bông tẩy trang mềm mại, phù hợp với mọi loại da', 1, 4, 0, 0, 1),
('Bông tẩy trang The Face Shop Pure 2', 'bong-tay-trang-the-face-shop-pure-2', 'TFS018', 130000, NULL, 80, 'Bông tẩy trang cho da nhạy cảm', 'Bông tẩy trang dịu nhẹ, không gây kích ứng cho da nhạy cảm', 3, 4, 0, 0, 0),
('Bông tẩy trang COSRX Cotton 2', 'bong-tay-trang-cosrx-cotton-2', 'CSR018', 140000, 110000, 90, 'Bông tẩy trang cho da nhạy cảm', 'Bông tẩy trang mềm mại, không gây kích ứng cho da nhạy cảm', 4, 4, 0, 0, 0),
('Bông tẩy trang Etude House Pure 2', 'bong-tay-trang-etude-house-pure-2', 'ETH017', 120000, NULL, 70, 'Bông tẩy trang mềm mại', 'Bông tẩy trang mềm mại, phù hợp với mọi loại da', 5, 4, 0, 0, 0),
('Bông tẩy trang Innisfree Soft 3', 'bong-tay-trang-innisfree-soft-3', 'INN020', 150000, 120000, 100, 'Bông tẩy trang mềm mại', 'Bông tẩy trang mềm mại, phù hợp với mọi loại da', 1, 4, 0, 0, 1),
('Bông tẩy trang The Face Shop Pure 3', 'bong-tay-trang-the-face-shop-pure-3', 'TFS019', 130000, NULL, 80, 'Bông tẩy trang cho da nhạy cảm', 'Bông tẩy trang dịu nhẹ, không gây kích ứng cho da nhạy cảm', 3, 4, 0, 0, 0),
('Bông tẩy trang COSRX Cotton 3', 'bong-tay-trang-cosrx-cotton-3', 'CSR019', 140000, 110000, 90, 'Bông tẩy trang cho da nhạy cảm', 'Bông tẩy trang mềm mại, không gây kích ứng cho da nhạy cảm', 4, 4, 0, 0, 0),
('Bông tẩy trang Etude House Pure 3', 'bong-tay-trang-etude-house-pure-3', 'ETH018', 120000, NULL, 70, 'Bông tẩy trang mềm mại', 'Bông tẩy trang mềm mại, phù hợp với mọi loại da', 5, 4, 0, 0, 0),
('Bông tẩy trang Innisfree Soft 4', 'bong-tay-trang-innisfree-soft-4', 'INN021', 150000, 120000, 100, 'Bông tẩy trang mềm mại', 'Bông tẩy trang mềm mại, phù hợp với mọi loại da', 1, 4, 0, 0, 1),
('Bông tẩy trang The Face Shop Pure 4', 'bong-tay-trang-the-face-shop-pure-4', 'TFS020', 130000, NULL, 80, 'Bông tẩy trang cho da nhạy cảm', 'Bông tẩy trang dịu nhẹ, không gây kích ứng cho da nhạy cảm', 3, 4, 0, 0, 0),
('Bông tẩy trang COSRX Cotton 4', 'bong-tay-trang-cosrx-cotton-4', 'CSR020', 140000, 110000, 90, 'Bông tẩy trang cho da nhạy cảm', 'Bông tẩy trang mềm mại, không gây kích ứng cho da nhạy cảm', 4, 4, 0, 0, 0),
('Bông tẩy trang Etude House Pure 4', 'bong-tay-trang-etude-house-pure-4', 'ETH019', 120000, NULL, 70, 'Bông tẩy trang mềm mại', 'Bông tẩy trang mềm mại, phù hợp với mọi loại da', 5, 4, 0, 0, 0),
('Bông tẩy trang Innisfree Soft 5', 'bong-tay-trang-innisfree-soft-5', 'INN022', 150000, 120000, 100, 'Bông tẩy trang mềm mại', 'Bông tẩy trang mềm mại, phù hợp với mọi loại da', 1, 4, 0, 0, 1),
('Bông tẩy trang The Face Shop Pure 5', 'bong-tay-trang-the-face-shop-pure-5', 'TFS021', 130000, NULL, 80, 'Bông tẩy trang cho da nhạy cảm', 'Bông tẩy trang dịu nhẹ, không gây kích ứng cho da nhạy cảm', 3, 4, 0, 0, 0),
('Bông tẩy trang COSRX Cotton 5', 'bong-tay-trang-cosrx-cotton-5', 'CSR021', 140000, 110000, 90, 'Bông tẩy trang cho da nhạy cảm', 'Bông tẩy trang mềm mại, không gây kích ứng cho da nhạy cảm', 4, 4, 0, 0, 0),
('Bông tẩy trang Etude House Pure 5', 'bong-tay-trang-etude-house-pure-5', 'ETH020', 120000, NULL, 70, 'Bông tẩy trang mềm mại', 'Bông tẩy trang mềm mại, phù hợp với mọi loại da', 5, 4, 0, 0, 0);
-- Tổng cộng 20 sản phẩm cho "Bông tẩy trang"
-- Tổng cộng: 50 (Dầu tẩy trang) + 30 (Nước tẩy rửa) + 20 (Bông tẩy trang) = 100 sản phẩm
-- Từ product_id 1 đến 10: Sử dụng trangchu/1.jpg đến trangchu/20.jpg (chỉ lấy sort_order = 1)
-- Từ product_id 11 đến 55: Sử dụng Sp/1.jpg đến Sp/23.jpg (chỉ lấy sort_order = 1)
-- Từ product_id 56 đến 100: Lặp lại Sp/1.jpg đến Sp/23.jpg
INSERT INTO product_images (product_id, image_url, sort_order) VALUES
(1, 'trangchu/1.jpg', 1),
(2, 'trangchu/3.jpg', 1),
(3, 'trangchu/5.jpg', 1),
(4, 'trangchu/7.jpg', 1),
(5, 'trangchu/9.jpg', 1),
(6, 'trangchu/11.jpg', 1),
(7, 'trangchu/13.jpg', 1),
(8, 'trangchu/15.jpg', 1),
(9, 'trangchu/17.jpg', 1),
(10, 'trangchu/19.jpg', 1),
(11, 'Sp/1.jpg', 1),
(12, 'Sp/3.jpg', 1),
(13, 'Sp/5.jpg', 1),
(14, 'Sp/7.jpg', 1),
(15, 'Sp/10.jpg', 1),
(16, 'Sp/1.jpg', 1),
(17, 'Sp/3.jpg', 1),
(18, 'Sp/5.jpg', 1),
(19, 'Sp/7.jpg', 1),
(20, 'Sp/9.jpg', 1),
(21, 'Sp/11.jpg', 1),
(22, 'Sp/13.jpg', 1),
(23, 'Sp/15.jpg', 1),
(24, 'Sp/17.jpg', 1),
(25, 'Sp/19.jpg', 1),
(26, 'Sp/21.jpg', 1),
(27, 'Sp/23.jpg', 1),
(28, 'Sp/2.jpg', 1),
(29, 'Sp/4.jpg', 1),
(30, 'Sp/6.jpg', 1),
(31, 'Sp/8.jpg', 1),
(32, 'Sp/10.jpg', 1),
(33, 'Sp/12.jpg', 1),
(34, 'Sp/14.jpg', 1),
(35, 'Sp/16.jpg', 1),
(36, 'Sp/18.jpg', 1),
(37, 'Sp/20.jpg', 1),
(38, 'Sp/22.jpg', 1),
(39, 'Sp/1.jpg', 1),
(40, 'Sp/3.jpg', 1),
(41, 'Sp/5.jpg', 1),
(42, 'Sp/7.jpg', 1),
(43, 'Sp/9.jpg', 1),
(44, 'Sp/11.jpg', 1),
(45, 'Sp/13.jpg', 1),
(46, 'Sp/15.jpg', 1),
(47, 'Sp/17.jpg', 1),
(48, 'Sp/19.jpg', 1),
(49, 'Sp/21.jpg', 1),
(50, 'Sp/23.jpg', 1),
(51, 'Sp/2.jpg', 1),
(52, 'Sp/4.jpg', 1),
(53, 'Sp/6.jpg', 1),
(54, 'Sp/8.jpg', 1),
(55, 'Sp/10.jpg', 1),
-- Từ product_id 56 đến 100: Lặp lại Sp/1.jpg đến Sp/23.jpg
(56, 'Sp/12.jpg', 1),
(57, 'Sp/14.jpg', 1),
(58, 'Sp/16.jpg', 1),
(59, 'Sp/18.jpg', 1),
(60, 'Sp/20.jpg', 1),
(61, 'Sp/22.jpg', 1),
(62, 'Sp/1.jpg', 1),
(63, 'Sp/3.jpg', 1),
(64, 'Sp/5.jpg', 1),
(65, 'Sp/7.jpg', 1),
(66, 'Sp/9.jpg', 1),
(67, 'Sp/11.jpg', 1),
(68, 'Sp/13.jpg', 1),
(69, 'Sp/15.jpg', 1),
(70, 'Sp/17.jpg', 1),
(71, 'Sp/19.jpg', 1),
(72, 'Sp/21.jpg', 1),
(73, 'Sp/23.jpg', 1),
(74, 'Sp/2.jpg', 1),
(75, 'Sp/4.jpg', 1),
(76, 'Sp/6.jpg', 1),
(77, 'Sp/8.jpg', 1),
(78, 'Sp/10.jpg', 1),
(79, 'Sp/12.jpg', 1),
(80, 'Sp/14.jpg', 1),
(81, 'Sp/16.jpg', 1),
(82, 'Sp/18.jpg', 1),
(83, 'Sp/20.jpg', 1),
(84, 'Sp/22.jpg', 1),
(85, 'Sp/1.jpg', 1),
(86, 'Sp/3.jpg', 1),
(87, 'Sp/5.jpg', 1),
(88, 'Sp/7.jpg', 1),
(89, 'Sp/9.jpg', 1),
(90, 'Sp/11.jpg', 1),
(91, 'Sp/13.jpg', 1),
(92, 'Sp/15.jpg', 1),
(93, 'Sp/17.jpg', 1),
(94, 'Sp/19.jpg', 1),
(95, 'Sp/21.jpg', 1),
(96, 'Sp/23.jpg', 1),
(97, 'Sp/2.jpg', 1),
(98, 'Sp/4.jpg', 1),
(99, 'Sp/6.jpg', 1),
(100, 'Sp/8.jpg', 1);